name: hatchet
description: Run hatchet on one or more files

# Define the resources needed for this pipeline.
resources:
  zones:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  - us-central1-f
  - us-east1-b
  - us-east1-c
  - us-east1-d

  # Create a data disk that is attached to the VM and destroyed when the
  # pipeline terminates.
  disks:
  - name: datadisk
    autoDelete: True

    # Within the Docker container, specify a mount point for the disk.
    mountPoint: /mnt/data

# Specify the Docker image to use along with the command
docker:
  imageName: gcr.io/durable-tracer-294016/hatchet

  # The Pipelines API will create the input directory when localizing files,
  # but does not create the output directory.
  cmd: >
    wget https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.fa.gz -O /hg19.fa.gz &&
    gunzip /hg19.fa.gz &&
    $HATCHET_PATHS_SAMTOOLS/samtools faidx /hg19.fa &&
    $HATCHET_PATHS_SAMTOOLS/samtools dict /hg19.fa > /hg19.dict &&
    export HATCHET_PATHS_REFERENCE=/hg19.fa &&
    BINSIZE=50kb ./_run.sh

# The Pipelines API currently supports GCS paths, along with patterns (globs),
# but it doesn't directly support a list of files being passed as a single input
# parameter ("gs://bucket/foo.bam gs://bucket/bar.bam").
inputParameters:
- name: normalbam
  description: Cloud Storage path of Normal BAM file
  localCopy:
    path: normal/
    disk: datadisk
- name: normalbai
  description: Cloud Storage path of Normal BAI file
  localCopy:
    path: normal/
    disk: datadisk
- name: tumorbam
  description: Cloud Storage path of Tumor BAM file
  localCopy:
    path: tumor/
    disk: datadisk
- name: tumorbai
  description: Cloud Storage path of Tumor BAI file
  localCopy:
    path: tumor/
    disk: datadisk

# By specifying an outputParameter, we instruct the pipelines API to
# copy /mnt/data/output/* to the Cloud Storage location specified in
# the pipelineArgs (see below).
outputParameters:
- name: outputPath
  description: Cloud Storage path for output
  localCopy:
    path: output/*
    disk: datadisk
