name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7]

    steps:
      - uses: actions/checkout@v2
      - name: Install Gurobi
        run: |
          wget https://packages.gurobi.com/9.0/gurobi9.0.2_linux64.tar.gz -O - | tar -xz
          (cd gurobi902/linux64/src/build && make)
          (cd gurobi902/linux64/lib && ln -f -s ../src/build/libgurobi_c++.a libgurobi_c++.a)
          export GUROBI_HOME=$(realpath gurobi902)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: GUROBI_HOME=${GUROBI_HOME} tox -e py
