name: CI

on:
  push:
    branches: [ master, develop, py3, ci ]
  pull_request:
    branches: [ master, develop, py3, ci ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox and any other packages
        run: |
          python -m pip install coverage tox tox-gh-actions

      - name: Test with tox
        run: |
          tox
        env:
          PLATFORM: ${{ matrix.python }}
          CXXFLAGS: -pthread

      - name: Convert coverage
        run: |
          python -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
