name: CI

on:
  push:
    branches: [ master, develop, py3, ci ]
  pull_request:
    branches: [ master, develop, py3, ci ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Gurobi
        run: |
          wget https://packages.gurobi.com/9.0/gurobi9.0.2_linux64.tar.gz -O gurobi9.0.2_linux64.tar.gz
          tar xvzf gurobi9.0.2_linux64.tar.gz
          (cd gurobi902/linux64/src/build && make)
          (cd gurobi902/linux64/lib && ln -f -s ../src/build/libgurobi_c++.a libgurobi_c++.a)
          echo ::set-env name=GUROBI_HOME::$(realpath gurobi902)

      - name: Activate Gurobi License
        run: |
          (cd gurobi902/linux64/bin && ./grbgetkey -q ${{ secrets.GUROBI_KEYCODE }})
          echo ::set-env name=GRB_LICENSE_FILE::/home/runner/gurobi.lic
        continue-on-error: true

     - name: check envvar
       run: |
           echo $GRB_LICENSE_FILE